SELECT T_MEMS.*, T_MEMS_LOGIN.EMAIL
FROM (members AS T_MEMS
	INNER JOIN members_login AS T_MEMS_LOGIN
    ON T_MEMS.MEMBERS_ID = T_MEMS_LOGIN.MEMBERS_ID
    and T_MEMS.MEMBERS_ID = 'M-02'
	)
	INNER JOIN gender_code AS T_GENDERS
    ON T_MEMS.GENDER_CODE_ID = T_GENDERS.GENDER_CODE_ID
where T_MEMS.MEMBERS_ID = 'M-02';